services:
  app:
    build: .
    environment:
      - PORT=8080
      - API_KEY=${API_KEY}
    volumes:
      - .:/app
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    ports:
      - "${PORT:-9000}:8080"
