services:
  app:
    build: .
    # image: arcoinnoregistry.azurecr.io/unstructured-job:latest
    environment:
      - SERVICE_BUS_CONNECTION_STRING=${SERVICE_BUS_CONNECTION_STRING}
      - QUEUE_NAME=${QUEUE_NAME}
      - BLOB_ENDPOINT=${BLOB_ENDPOINT}
      - BLOB_ACCESS_KEY=${BLOB_ACCESS_KEY}
      - BLOB_SECRET_KEY=${BLOB_SECRET_KEY}
      - BLOB_BUCKET=documents
      - WALLY_URL=${WALLY_URL}
      - WALLY_BEARER=${WALLY_BEARER}
    volumes:
      - .:/app
    command:
      # bash -c "pip list
      # && cat requirements.txt
      # && python3 src/main.py"
      ["python3", "src/main.py"]
    ports:
      - "${PORT:-9000}:8080"
    networks:
      - arco-wally_minio_network
networks:
  arco-wally_minio_network:
    external: true
