services:
  unstructured:
    build:
      context: .
      dockerfile: unstructured_src/lib.Dockerfile
    profiles: ['all', 'unstructured']
    environment:
      - SERVICE_BUS_CONNECTION_STRING=${UNSTRUCTURED_QUEUE_CONNECTION_STRING}
      - QUEUE_NAME=${UNSTRUCTURED_QUEUE_NAME}
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${PORT:-9100}:8080"
    networks:
      - arco-wally_minio_network
  extractous:
    build:
      context: .
      dockerfile: extractous_src/Dockerfile
    profiles: ['all', 'extractous']
    env_file:
      - .env
    environment:
      - SERVICE_BUS_CONNECTION_STRING=${EXTRACTOUS_QUEUE_CONNECTION_STRING}
      - QUEUE_NAME=${EXTRACTOUS_QUEUE_NAME}
    volumes:
      - .:/app
    ports:
      - "${PORT:-9200}:8080"
    networks:
      - arco-wally_minio_network
networks:
  arco-wally_minio_network:
    external: true
