name: Trigger auto build for unstructured-job

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ jobify ]
    paths:
    - '**'
    - '.github/workflows/unstructured-job-AutoBuildTrigger.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo
    env:
      BLOB_ENDPOINT: https://arcoprodwallystorage.blob.core.windows.net/
      BLOB_ACCESS_KEY: arcoprodwallystorage
      BLOB_BUCKET: documents
      WALLY_URL: https://wally-arco-v2.blackplant-1feb3b88.eastus.azurecontainerapps.io
      QUEUE_MESSAGE_COUNT: 10
      QUEUE_WAIT_TIME: 5
      
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.UNSTRUCTUREDAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.UNSTRUCTUREDAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.UNSTRUCTUREDAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push Unstructured container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: arcoinnoregistry.azurecr.io
          registryUsername: ${{ secrets.UNSTRUCTUREDAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.UNSTRUCTUREDAPI_REGISTRY_PASSWORD }}
          containerAppName: unstructured-job
          resourceGroup: ARCO-PROD-Innovation-RG-01
          dockerfilePath: unstructured_src/Dockerfile
          imageToBuild: arcoinnoregistry.azurecr.io/unstructured-job:${{ github.sha }}
          environmentVariables: |
            BLOB_ENDPOINT=$BLOB_ENDPOINT
            BLOB_ACCESS_KEY=$BLOB_ACCESS_KEY
            BLOB_SECRET_KEY=${{ secrets.BLOB_SECRET_KEY }}
            BLOB_BUCKET=$BLOB_BUCKET
            SERVICE_BUS_CONNECTION_STRING=${{ secrets.EXTRACTOUS_CONNECTION_STRING }}
            QUEUE_NAME=wally-to-extractous
            WALLY_URL=$WALLY_URL
            WALLY_BEARER=${{ secrets.WALLY_BEARER }}
            QUEUE_MESSAGE_COUNT=$QUEUE_MESSAGE_COUNT
            QUEUE_WAIT_TIME=$QUEUE_WAIT_TIME

      - name: Build and push Extractous container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: arcoinnoregistry.azurecr.io
          registryUsername: ${{ secrets.UNSTRUCTUREDAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.UNSTRUCTUREDAPI_REGISTRY_PASSWORD }}
          containerAppName: extractous-job
          resourceGroup: ARCO-PROD-Innovation-RG-01
          dockerfilePath: extractous_src/Dockerfile
          imageToBuild: arcoinnoregistry.azurecr.io/extractous-job:${{ github.sha }}
          environmentVariables: |
            BLOB_ENDPOINT=$BLOB_ENDPOINT
            BLOB_ACCESS_KEY=$BLOB_ACCESS_KEY
            BLOB_SECRET_KEY=${{ secrets.BLOB_SECRET_KEY }}
            BLOB_BUCKET=$BLOB_BUCKET
            SERVICE_BUS_CONNECTION_STRING=${{ secrets.UNSTRUCTURED_CONNECTION_STRING }}
            QUEUE_NAME=wally-to-unstructured
            WALLY_URL=$WALLY_URL
            WALLY_BEARER=${{ secrets.WALLY_BEARER }}
            QUEUE_MESSAGE_COUNT=$QUEUE_MESSAGE_COUNT
            QUEUE_WAIT_TIME=$QUEUE_WAIT_TIME
